import { CoreError } from "@do-soul/alaya-core";
import {
  DirtyStatePanicPayloadSchema,
  Phase5EventType,
  PhaseBEventType,
  SoulApprovalRequestedPayloadSchema,
  type DirtyStatePanicPayload,
  type EventLogEntry,
  type SoulApprovalRequestedPayload
} from "@do-soul/alaya-protocol";
import type { Hono } from "hono";
import { parseJsonBody } from "./shared.js";

export interface E2eEventTriggerRouteServices {
  readonly runService: {
    getById(runId: string): Promise<{
      readonly run_id: string;
      readonly workspace_id: string;
    }>;
  };
  readonly eventLogRepo: {
    append(
      event: Omit<EventLogEntry, "event_id" | "created_at" | "revision"> & {
        readonly revision?: number;
      }
    ): Promise<EventLogEntry>;
  };
  readonly runtimeNotifier: {
    notifyEntry(entry: EventLogEntry): void | Promise<void>;
  };
  readonly now?: () => string;
}

export function registerE2eEventTriggerRoutes(
  app: Hono,
  services: E2eEventTriggerRouteServices
): void {
  app.post("/__e2e/events/soul-approval-requested", async (context) => {
    const body = await parseBodyRecord(context.req.json.bind(context.req));
    const runId = readRequiredString(body, "run_id");
    const run = await services.runService.getById(runId);
    const approvalId = readOptionalString(body, "approval_id") ?? makeId("approval", run.run_id);
    const messageId = readOptionalString(body, "message_id") ?? makeId("message", run.run_id);
    const description =
      readOptionalString(body, "description") ??
      "E2E approval request generated by the deterministic test trigger.";
    const riskLevel = readOptionalString(body, "risk_level");

    const payloadInput: Record<string, unknown> = {
      message_id: messageId,
      approval_id: approvalId,
      description,
      run_id: run.run_id
    };
    if (riskLevel !== undefined) {
      payloadInput.risk_level = riskLevel;
    }

    const payload = parseSoulApprovalRequestedPayload(payloadInput);
    const entry = await appendAndBroadcast(services, {
      event_type: Phase5EventType.SOUL_APPROVAL_REQUESTED,
      entity_type: "approval",
      entity_id: payload.approval_id,
      workspace_id: run.workspace_id,
      run_id: run.run_id,
      caused_by: "e2e_event_trigger",
      revision: 0,
      payload_json: payload
    });

    return context.json(
      {
        success: true,
        data: {
          event_id: entry.event_id,
          approval_id: payload.approval_id,
          message_id: payload.message_id,
          run_id: run.run_id
        }
      },
      201
    );
  });

  app.post("/__e2e/events/dirty-state-panic", async (context) => {
    const body = await parseBodyRecord(context.req.json.bind(context.req));
    const runId = readRequiredString(body, "run_id");
    const run = await services.runService.getById(runId);
    const workerRunId = readOptionalString(body, "worker_run_id") ?? makeId("worker-run", run.run_id);
    const dossierId = readOptionalString(body, "dossier_id") ?? makeId("dossier", run.run_id);
    const trigger = readOptionalString(body, "trigger") ?? "manual";
    const panicSource = readOptionalString(body, "panic_source") ?? "e2e_event_trigger";
    const panicSummary =
      readOptionalString(body, "panic_summary") ??
      "Deterministic E2E dirty-state panic trigger.";
    const affectedEntityCount = readOptionalNonNegativeInt(body, "affected_entity_count") ?? 1;

    const payload = parseDirtyStatePanicPayload({
      dossier_id: dossierId,
      worker_run_id: workerRunId,
      principal_run_id: run.run_id,
      trigger,
      panic_source: panicSource,
      panic_summary: panicSummary,
      affected_entity_count: affectedEntityCount
    });
    const entry = await appendAndBroadcast(services, {
      event_type: PhaseBEventType.DIRTY_STATE_PANIC,
      entity_type: "worker_run",
      entity_id: payload.worker_run_id,
      workspace_id: run.workspace_id,
      run_id: run.run_id,
      caused_by: "e2e_event_trigger",
      revision: 0,
      payload_json: payload
    });

    return context.json(
      {
        success: true,
        data: {
          event_id: entry.event_id,
          dossier_id: payload.dossier_id,
          worker_run_id: payload.worker_run_id,
          run_id: run.run_id
        }
      },
      201
    );
  });
}

async function appendAndBroadcast(
  services: E2eEventTriggerRouteServices,
  event: Omit<EventLogEntry, "event_id" | "created_at">
): Promise<EventLogEntry> {
  const entry = await services.eventLogRepo.append(event);
  await services.runtimeNotifier.notifyEntry(entry);
  return entry;
}

async function parseBodyRecord(readJson: () => Promise< unknown>): Promise<Record<string, unknown>> {
  const body = await parseJsonBody(readJson);
  if (typeof body !== "object" || body === null || Array.isArray(body)) {
    throw new CoreError("VALIDATION", "Invalid request body");
  }
  return body as Record<string, unknown>;
}

function readRequiredString(body: Readonly<Record<string, unknown>>, key: string): string {
  const value = readOptionalString(body, key);
  if (value === undefined) {
    throw new CoreError("VALIDATION", `${key} is required`);
  }
  return value;
}

function readOptionalString(body: Readonly<Record<string, unknown>>, key: string): string | undefined {
  const value = body[key];
  if (value === undefined) {
    return undefined;
  }
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new CoreError("VALIDATION", `${key} must be a non-empty string`);
  }
  return value.trim();
}

function readOptionalNonNegativeInt(
  body: Readonly<Record<string, unknown>>,
  key: string
): number | undefined {
  const value = body[key];
  if (value === undefined) {
    return undefined;
  }
  if (typeof value !== "number" || !Number.isInteger(value) || value < 0) {
    throw new CoreError("VALIDATION", `${key} must be a non-negative integer`);
  }
  return value;
}

function parseSoulApprovalRequestedPayload(input: Record<string, unknown>): SoulApprovalRequestedPayload {
  const result = SoulApprovalRequestedPayloadSchema.safeParse(input);
  if (!result.success) {
    throw new CoreError("VALIDATION", "Invalid soul.approval_requested payload", { cause: result.error });
  }
  return result.data;
}

function parseDirtyStatePanicPayload(input: Record<string, unknown>): DirtyStatePanicPayload {
  const result = DirtyStatePanicPayloadSchema.safeParse(input);
  if (!result.success) {
    throw new CoreError("VALIDATION", "Invalid dirty_state.panic payload", { cause: result.error });
  }
  return result.data;
}

function makeId(prefix: string, runId: string): string {
  return `e2e-${prefix}-${runId}-${Date.now()}`;
}
