import { CoreError } from "@do-soul/alaya-core";
import {
  DirtyStatePanicPayloadSchema,
  FileApprovalEventType,
  ObligationTrustNarrativeEventType,
  SoulApprovalRequestedPayloadSchema,
  type DirtyStatePanicPayload,
  type EventLogEntry,
  type SoulApprovalRequestedPayload
} from "@do-soul/alaya-protocol";
import type { Hono } from "hono";
import { parseJsonBody } from "./shared.js";

export interface E2eEventTriggerRouteServices {
  readonly runService: {
    getById(runId: string): Promise<{
      readonly run_id: string;
      readonly workspace_id: string;
    }>;
  };
  readonly eventLogRepo: {
    append(
      event: Omit<EventLogEntry, "event_id" | "created_at" | "revision"> & {
        readonly revision?: number;
      }
    ): Promise<EventLogEntry>;
  };
  readonly runtimeNotifier: {
    notifyEntry(entry: EventLogEntry): void | Promise<void>;
  };
  readonly now?: () => string;
}

export function registerE2eEventTriggerRoutes(
  app: Hono,
  services: E2eEventTriggerRouteServices
): void {
  registerSoulApprovalRequestedRoute(app, services);
  registerDirtyStatePanicRoute(app, services);
}

function registerSoulApprovalRequestedRoute(
  app: Hono,
  services: E2eEventTriggerRouteServices
): void {
  app.post("/__e2e/events/soul-approval-requested", async (context) => {
    const body = await parseBodyRecord(context.req.json.bind(context.req));
    const run = await loadTriggeredRun(services, body);
    const payload = createSoulApprovalRequestedEvent(body, run.run_id);
    const entry = await appendAndBroadcast(services, {
      event_type: FileApprovalEventType.SOUL_APPROVAL_REQUESTED,
      entity_type: "approval",
      entity_id: payload.approval_id,
      workspace_id: run.workspace_id,
      run_id: run.run_id,
      caused_by: "e2e_event_trigger",
      payload_json: payload
    });

    return context.json({
      success: true,
      data: {
        event_id: entry.event_id,
        approval_id: payload.approval_id,
        message_id: payload.message_id,
        run_id: run.run_id
      }
    }, 201);
  });
}

function registerDirtyStatePanicRoute(
  app: Hono,
  services: E2eEventTriggerRouteServices
): void {
  app.post("/__e2e/events/dirty-state-panic", async (context) => {
    const body = await parseBodyRecord(context.req.json.bind(context.req));
    const run = await loadTriggeredRun(services, body);
    const payload = createDirtyStatePanicEvent(body, run.run_id);
    const entry = await appendAndBroadcast(services, {
      event_type: ObligationTrustNarrativeEventType.DIRTY_STATE_PANIC,
      entity_type: "worker_run",
      entity_id: payload.worker_run_id,
      workspace_id: run.workspace_id,
      run_id: run.run_id,
      caused_by: "e2e_event_trigger",
      payload_json: payload
    });

    return context.json({
      success: true,
      data: {
        event_id: entry.event_id,
        dossier_id: payload.dossier_id,
        worker_run_id: payload.worker_run_id,
        run_id: run.run_id
      }
    }, 201);
  });
}

async function loadTriggeredRun(
  services: E2eEventTriggerRouteServices,
  body: Readonly<Record<string, unknown>>
) {
  const runId = readRequiredString(body, "run_id");
  return await services.runService.getById(runId);
}

function createSoulApprovalRequestedEvent(
  body: Readonly<Record<string, unknown>>,
  runId: string
): SoulApprovalRequestedPayload {
  const payloadInput: Record<string, unknown> = {
    message_id: readOptionalString(body, "message_id") ?? makeId("message", runId),
    approval_id: readOptionalString(body, "approval_id") ?? makeId("approval", runId),
    description:
      readOptionalString(body, "description") ??
      "E2E approval request generated by the deterministic test trigger.",
    run_id: runId
  };
  const riskLevel = readOptionalString(body, "risk_level");
  if (riskLevel !== undefined) {
    payloadInput.risk_level = riskLevel;
  }
  return parseSoulApprovalRequestedPayload(payloadInput);
}

function createDirtyStatePanicEvent(
  body: Readonly<Record<string, unknown>>,
  runId: string
): DirtyStatePanicPayload {
  return parseDirtyStatePanicPayload({
    dossier_id: readOptionalString(body, "dossier_id") ?? makeId("dossier", runId),
    worker_run_id: readOptionalString(body, "worker_run_id") ?? makeId("worker-run", runId),
    principal_run_id: runId,
    trigger: readOptionalString(body, "trigger") ?? "manual",
    panic_source: readOptionalString(body, "panic_source") ?? "e2e_event_trigger",
    panic_summary:
      readOptionalString(body, "panic_summary") ??
      "Deterministic E2E dirty-state panic trigger.",
    affected_entity_count: readOptionalNonNegativeInt(body, "affected_entity_count") ?? 1
  });
}

async function appendAndBroadcast(
  services: E2eEventTriggerRouteServices,
  event: Omit<EventLogEntry, "event_id" | "created_at" | "revision">
): Promise<EventLogEntry> {
  const entry = await services.eventLogRepo.append(event);
  await services.runtimeNotifier.notifyEntry(entry);
  return entry;
}

async function parseBodyRecord(readJson: () => Promise< unknown>): Promise<Record<string, unknown>> {
  const body = await parseJsonBody(readJson);
  if (typeof body !== "object" || body === null || Array.isArray(body)) {
    throw new CoreError("VALIDATION", "Invalid request body");
  }
  return body as Record<string, unknown>;
}

function readRequiredString(body: Readonly<Record<string, unknown>>, key: string): string {
  const value = readOptionalString(body, key);
  if (value === undefined) {
    throw new CoreError("VALIDATION", `${key} is required`);
  }
  return value;
}

function readOptionalString(body: Readonly<Record<string, unknown>>, key: string): string | undefined {
  const value = body[key];
  if (value === undefined) {
    return undefined;
  }
  if (typeof value !== "string" || value.trim().length === 0) {
    throw new CoreError("VALIDATION", `${key} must be a non-empty string`);
  }
  return value.trim();
}

function readOptionalNonNegativeInt(
  body: Readonly<Record<string, unknown>>,
  key: string
): number | undefined {
  const value = body[key];
  if (value === undefined) {
    return undefined;
  }
  if (typeof value !== "number" || !Number.isInteger(value) || value < 0) {
    throw new CoreError("VALIDATION", `${key} must be a non-negative integer`);
  }
  return value;
}

function parseSoulApprovalRequestedPayload(input: Record<string, unknown>): SoulApprovalRequestedPayload {
  const result = SoulApprovalRequestedPayloadSchema.safeParse(input);
  if (!result.success) {
    throw new CoreError("VALIDATION", "Invalid soul.approval_requested payload", { cause: result.error });
  }
  return result.data;
}

function parseDirtyStatePanicPayload(input: Record<string, unknown>): DirtyStatePanicPayload {
  const result = DirtyStatePanicPayloadSchema.safeParse(input);
  if (!result.success) {
    throw new CoreError("VALIDATION", "Invalid dirty_state.panic payload", { cause: result.error });
  }
  return result.data;
}

function makeId(prefix: string, runId: string): string {
  return `e2e-${prefix}-${runId}-${Date.now()}`;
}
