export type CoverageBinding = "contract-only" | "real-producer" | "incomplete";

export type CoverageRow = Readonly<{
  readonly id: string;
  readonly requirement: string;
  readonly expected: string;
  readonly planted_failure: string;
  readonly producer: string;
  readonly consumer: string;
  readonly binding: CoverageBinding;
  readonly incomplete_reason?: string;
}>;

export const COVERAGE_ROWS: readonly CoverageRow[] = Object.freeze([
  row("A01", "yesterday anchors failed deployment; last-week config associated",
    "r=1000 yesterday; c=850 last-week; guard on r only",
    "applying yesterday to every output removes c",
    "compileConditionalFieldQuery + observeField", "MCP encode index", "real-producer"),
  row("A02", "prior same-service failure is contextual history with unknown cause",
    "h=550 claim=unknown; routing s hidden",
    "requiring proven causal identity excludes h or fabricates supported",
    "assessUnknownCause", "MCP unknown-cause index", "real-producer"),
  row("A03", "epsilon/empty/sequence/alternative/guards/bindings differ",
    "epsilon≠empty; hypothesis×binding rows stay distinct",
    "empty accepted as epsilon; bindings pooled",
    "interpretFiniteProgram + compileConditionalFieldQuery", "typed observeProgram", "real-producer"),
  row("A04", "long chains and fan-out keep association without hop attenuation",
    "n20=900; each h_i=550",
    "unlimited semantic spread hidden behind a resource cap",
    "enumerateSimplePaths independent", "none", "contract-only"),
  row("A05", "finite scalar solver agrees with independent path enumeration",
    "DEPLOYMENT_MILLIGRADES; cycle a=1000 b=900 c=800",
    "duplicate/cycle amplification",
    "produceField vs enumerateSimplePaths", "boundPorts", "real-producer"),
  row("A06", "same-path uses one compatible joint label",
    "same_path(.9,.2)+(.2,.9) rejects at 800",
    "coordinate-wise max fabricates (.9,.9)",
    "evaluateFacets independent; projectAcceptingIndex", "index entries", "real-producer"),
  row("A07", "hyperedge AND/OR retain bindings and support",
    "AND requires one binding; OR keeps complete witnesses",
    "separate reachable premises become a complete conjunction",
    "joinHyperedgeAnd/Or independent", "typed hyperedge observe", "contract-only"),
  row("A08", "cheapest feasible complete explanation remains available",
    "cheap cost=400 over expensive=1200",
    "canonical strongest/first path hides cheap witness",
    "cheapestCompleteWitness independent", "index explanation_ids", "contract-only"),
  row("A09", "interrupt/resume observes the same pinned coverage",
    "truncated-zero → interrupted/open, not exhausted_empty",
    "interrupted zero rows become known-empty; cursor skips/duplicates",
    "mapNativeReaderPage + runRecall interrupted readers", "SQLite resume", "real-producer"),
  row("A10", "seed/adjacency/guard/binding regions remain represented",
    "four open regions after partial run",
    "queue omission or ANN absence creates false closure",
    "oracle open_regions", "observer residuals", "contract-only"),
  row("A11", "fair work, memory, reserved finalization hold",
    "finite region served; reserve untouched",
    "high-bound refinement starves a finite region",
    "scheduleFairWork independent", "F5 work_units counters", "real-producer"),
  row("A12", "empty finite authorized scope can close; unavailable stays open",
    "exhausted_empty vs unavailable vs cancelled",
    "unavailable producer reported as complete empty",
    "runConditionalFieldRecall empty/unavailable readers", "MCP A12", "real-producer"),
  row("A13", "complete index may contain explicit unknown cause",
    "logical_index=complete and claim=unknown coexist",
    "every fact must be proved, or unresolved fields disappear",
    "projectOracleIndex claims map", "MCP unknown-cause", "real-producer"),
  row("A14", "stable pages retain snapshot/query/authorization identity",
    "pages concatenate; identities match",
    "next page changes snapshot or reselects by old ranker",
    "projectOracleIndex paging + handler pages", "MCP/CLI continuation", "real-producer"),
  row("A15", "logical index, inline portion and payload status differ",
    "first page transport=partial, continuation set",
    "first page called full inline delivery",
    "pageMasqueradesAsFullIndex", "MCP A15", "real-producer"),
  row("A16", "output includes index roles/association/explanation at MCP/CLI",
    "handler results order equals index entries",
    "outer handler silently selects a different top-K",
    "createRecallHandler + CLI tools call", "MCP/CLI", "real-producer"),
  row("A17", "normal Recall never enqueues extraction or calls a provider",
    "provider_calls=0 garden_enqueue=0",
    "missing optional projection triggers remote work",
    "runRecall pendingGarden length", "handler counters", "real-producer"),
  row("A18", "write/restart/tombstone/revoke reaches the same reader",
    "tombstone hidden after reopen; mixed snapshot invalidates",
    "mixed generation or resurrected memory",
    "SQLite reopen + tombstone", "handler A18", "real-producer"),
  row("A19", "unknown/correlated evidence has honest claim state",
    "duplicate source sets do not mint independence",
    "duplicate paths/source count mint support",
    "F3 explanation leak check", "handler F3", "real-producer"),
  row("A20", "actual-budget representation respects feasibility",
    "page_budget is not a complete universe; memory_bytes=1 stays open",
    "density/identity caps masquerade as optimum",
    "F5 tiny memory index", "handler token cap", "real-producer"),
  row("A21", "normal entry is target-only before deletion",
    "no ranking_authority/delivery_path/strategy_mix on target payload; retired flags not dispatched",
    "flags or worker dispatch reach the old decision chain",
    "executeRecall import census (U07)", "MCP forbidden keys", "incomplete",
    "physical absence is D00; U06 plants exclusivity only"),
  row("A22", "public/persisted old states have explicit dispositions",
    "persisted_old_receipts freeze-live; rebuildable already-migrated; feedback unreachable-on-target",
    "silent reinterpretation, mixed schema, fallback decision route",
    "COMPATIBILITY_LEDGER freeze", "none until D01 packaging", "incomplete",
    "final migration packaging remains D/T work"),
  row("B01", "product identity preserves object/hypothesis/program/binding/time",
    "five-tuple accepting key; program_state+time_state required on public entries",
    "equal object IDs merge incompatible states",
    "projectAcceptingIndex IndexEntry", "MCP index entries", "real-producer"),
  row("B02", "derivation scalar agrees with max-min; explanation coverage is separate",
    "AND=min OR=max; fixed_point ≠ witnesses complete",
    "numeric agreement claims all observers complete",
    "U02 Derivation store", "index support_work", "real-producer"),
  row("B03", "equal-score AND/OR withdraw c distinctly",
    "(a AND b) OR c → AND{a,b}; (a OR b) AND c → undefined",
    "both structures collapse to the same revision",
    "U02/U03 derivation revision", "none", "real-producer"),
  row("B04", "same-service history retains service binding across shared infrastructure",
    "service-role history hangs off uses_service; provider bridge does not unify another service",
    "all-high-grade provider bridge admits another service",
    "SQLite plant + compileConditionalFieldQuery / observeField", "MCP same-service query", "real-producer"),
  row("B05", "compiler interpretation coverage reaches the public index honestly",
    "omitted hypotheses keep interpretation_coverage=open while observed_coverage may complete",
    "completing one interpretation produces certainty about omitted hypotheses",
    "projectAcceptingIndex CompletenessReport", "MCP completeness", "real-producer"),
  row("B06", "revised-source evaluation agrees with fresh evaluation; mixed epochs invalidate",
    "public epoch tuple mismatch → invalidate/restart; same tuple → refine",
    "old source/model/interpretation silently refines a new epoch",
    "continuationInvalidated + interpretation_id", "paged resume", "real-producer"),
  row("B07", "recovered explanations preserve dependency versions and intermediate authorization",
    "revoked intermediate makes explanation unrecoverable even if grade is cached",
    "available endpoint or cached grade bypasses a revoked intermediate",
    "U02/U03/U04 support recovery", "expansion payload", "real-producer"),
  row("B08", "bounded observations/joins/continuation retain unfinished regions",
    "required unfinished regions survive numerical stability and cursor advance",
    "memory eviction or cursor reset erases required work",
    "FIELD_RESUME + observer cursors", "worker/RPC resume", "real-producer"),
  row("B09", "affordable complete alternative explanations remain available",
    "cheap complete witness retained when scalar winner differs",
    "winning scalar deletes a needed weaker/cheaper witness",
    "selectFeasibleWitnesses", "index explanation_ids", "real-producer"),
  row("B10", "output-level and witness-level reports preserve grain and exposure",
    "output grain credits output_id only; witness grain requires exposed witness_id",
    "output-only or forged receipt credits every path",
    "U05 UsageReport", "MCP usage handler", "real-producer"),
  row("B11", "duplicates, nonexposure, unknown use, correlation, ordinal scale stay distinct",
    "duplicate identity counted once; missing ≠ negative; nonexposure ≠ unused",
    "missing reports become negatives or discount arithmetic revises semantic truth",
    "U05 foldReports", "usage receipts", "real-producer"),
  row("B12", "scheduled plasticity and watermark consumers obey update ownership",
    "operational_feedback unreachable-on-target for PathRelation.strength",
    "new helper is safe but old background path still mutates unsupported strength",
    "projectCausalUsageOntoPaths still exported", "Garden path_plasticity_update", "real-producer"),
  row("B13", "upgraded fields reach SQLite, worker/RPC, MCP/CLI, paging, expansion, usage",
    "index product identity and interpretation_coverage survive real dispatch",
    "contract tests pass while dispatch flattens fields, invokes a provider, or selects again",
    "runConditionalFieldRecall + handler index", "MCP/CLI/worker", "incomplete",
    "worker source already calls runConditionalFieldRecall; worker acceptance still spawns gitignored dist that can skew from source"),
  row("B14", "no-learner reference and completed necessity dispositions",
    "four mechanisms NOT_REQUIRED or BENEFIT_NOT_ESTABLISHED; finite examples ≠ learning gains",
    "a deferred selected mechanism is called complete",
    "U05 necessity table", "operational no-learner Recall", "real-producer"),
  row("F1", "distinct programs/filters",
    "epsilon/empty/forward/reversed/blocked differ on one graph; public filters do not dump every fact",
    "all programs collapse to one field",
    "observeProgram + handler dimension/domain_tags", "MCP F1", "real-producer"),
  row("F2", "tombstone/scope/expired stay out of seed/intermediate/target/preview",
    "SECRET/GLOBAL/EXPIRED absent",
    "ineligible rows appear in index or preview",
    "runRecall authorized_scopes", "handler F2", "real-producer"),
  row("F3", "witness identity does not leak across objects",
    "explanation_ids do not copy another object's witnesses; unknown remains representable",
    "cross-object witness ids",
    "runRecall + handler", "MCP F3", "real-producer"),
  row("F4", "40-match/32-cap resume equals full observation",
    "concatenated pages = full ids, no skip/duplicate",
    "32-cap silently drops remainder",
    "runRecall nativeLimit 32", "handler paging", "incomplete",
    "FIELD_RESUME process-local; worker 32-cap unbound"),
  row("F5", "work_units/memory_bytes/token_estimate are actual",
    "nativeVisits≤work_units; memory_bytes=1 not complete 31; tokens follow preview bytes",
    "token_estimate frozen at 1",
    "countingReaders + encodeIndexResults", "handler F5", "real-producer"),
  row("F6", "pin and preview are not mixed across snapshot commit",
    "one generation of previews; mixed before/after forbidden",
    "mixed-generation complete payload",
    "runRecall pin/source log", "handler F6", "incomplete",
    "local pin closed; mixed-generation test remains weak on worker"),
  row("F7", "midnight continuation is invalidated or same-instance",
    "interpretation_clock change invalidates or keeps identity; no two-day splice",
    "pages spliced across midnight",
    "runRecall clocks", "handler F7", "incomplete",
    "clock is not in continuation identity on all producers"),
  row("F8", "worker-port preview/RPC residual",
    "content_preview is the pinned source excerpt, not omitted placeholder",
    "worker port supplies empty preview map so MCP hydrates [payload omitted]",
    "executeRecall conditionalFieldPort branch", "MCP encodeIndexResults", "real-producer"),
  row("NT3", "A09/A18 lifecycle tests are real SQLite, not stubs",
    "tombstone restart and interrupted-zero use openSourceSlice",
    "stubbed lifecycle always-green",
    "source-lifecycle-oracle + acceptance", "handler A18", "real-producer"),
  row("S13", "worker + CLI planted slice",
    "CLI in-process matches handler index identity",
    "CLI marshalling uses stub deps while claiming planted slice",
    "createToolsCommand + RecallService", "CLI soul.recall", "incomplete",
    "CLI in-process bound; worker RPC unbound")
]);

export function coverageById(id: string): CoverageRow {
  const found = COVERAGE_ROWS.find((row) => row.id === id);
  if (found === undefined) throw new Error(`coverage row missing: ${id}`);
  return found;
}

export function requiredIds(): readonly string[] {
  const a = Array.from({ length: 22 }, (_, index) => `A${String(index + 1).padStart(2, "0")}`);
  const b = Array.from({ length: 14 }, (_, index) => `B${String(index + 1).padStart(2, "0")}`);
  return [...a, ...b, "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "NT3", "S13"];
}

export function formatCoverageMarkdown(rows: readonly CoverageRow[] = COVERAGE_ROWS): string {
  const header = [
    "# U06 coverage table",
    "",
    "Independent expected outcomes live in `upgrade-expected.ts` / existing A-row oracles.",
    "Producer binding is live-inspected; incomplete means U07 (or the named owner) must bind, not that the row is skipped.",
    "",
    "| ID | Binding | Expected | Planted failure | Producer | Consumer | Incomplete reason |",
    "| --- | --- | --- | --- | --- | --- | --- |"
  ];
  const body = rows.map((row) => [
    row.id,
    row.binding,
    escapeCell(row.expected),
    escapeCell(row.planted_failure),
    escapeCell(row.producer),
    escapeCell(row.consumer),
    escapeCell(row.incomplete_reason ?? "")
  ].join(" | ")).map((line) => `| ${line} |`);
  return `${header.join("\n")}\n${body.join("\n")}\n`;
}

function row(
  id: string,
  requirement: string,
  expected: string,
  planted_failure: string,
  producer: string,
  consumer: string,
  binding: CoverageBinding,
  incomplete_reason?: string
): CoverageRow {
  return Object.freeze({
    id,
    requirement,
    expected,
    planted_failure,
    producer,
    consumer,
    binding,
    ...(incomplete_reason === undefined ? {} : { incomplete_reason })
  });
}

function escapeCell(value: string): string {
  return value.replaceAll("|", "/");
}
