export type CoverageBinding = "contract-only" | "real-producer" | "incomplete";

export const COVERAGE_EVIDENCE_SCOPE = "real-producer identifies exercised production classes, not a real-world dataset or KPI. "
  + "Most fixtures are small synthetic SQLite graphs. scale-delivery.test.ts adds 1,024 synthetic sources with 180 lexical matches, "
  + "48 matches at work=120/reserve=30 including reverse/interleaved UUID arrival, 12 out-of-order relation targets, "
  + "1,024 matches exceeding default retained memory, and zero/one-work termination. "
  + "These are deterministic direct-runtime regressions; full benchmark snapshots, query quality, and thousand-source worker/CLI scale are not established by this ledger.";

export type CoverageRow = Readonly<{
  readonly id: string;
  readonly requirement: string;
  readonly expected: string;
  readonly planted_failure: string;
  readonly producer: string;
  readonly consumer: string;
  readonly binding: CoverageBinding;
  readonly incomplete_reason?: string;
}>;

export const COVERAGE_ROWS: readonly CoverageRow[] = Object.freeze([
  row("A01", "yesterday anchors failed deployment; last-week config associated",
    "r=1000 yesterday; c=850 last-week; guard on r only",
    "applying yesterday to every output removes c",
    "compileConditionalFieldQuery + observeField", "MCP encode index", "real-producer"),
  row("A02", "prior same-service failure is contextual history with unknown cause",
    "h=550 claim=unknown; routing s hidden",
    "requiring proven causal identity excludes h or fabricates supported",
    "assessUnknownCause", "MCP unknown-cause index", "real-producer"),
  row("A03", "epsilon/empty/sequence/alternative/guards/bindings differ",
    "epsilon≠empty; hypothesis×binding rows stay distinct",
    "empty accepted as epsilon; bindings pooled",
    "interpretFiniteProgram + compileConditionalFieldQuery", "typed observeProgram", "real-producer"),
  row("A04", "long chains and fan-out keep association without hop attenuation",
    "n20=900; each h_i=550",
    "unlimited semantic spread hidden behind a resource cap",
    "field-engine.ts createConditionalField; field-engine.test.ts long homogeneous / fan-out", "none", "real-producer"),
  row("A05", "finite scalar solver agrees with independent path enumeration",
    "DEPLOYMENT_MILLIGRADES; cycle a=1000 b=900 c=800",
    "duplicate/cycle amplification",
    "produceField vs enumerateSimplePaths", "boundPorts", "real-producer"),
  row("A06", "same-path uses one compatible joint label",
    "same_path(.9,.2)+(.2,.9) rejects at 800",
    "coordinate-wise max fabricates (.9,.9)",
    "evaluateFacets independent; projectAcceptingIndex", "index entries", "real-producer"),
  row("A07", "hyperedge AND/OR retain bindings and support",
    "AND requires one binding; OR keeps complete witnesses",
    "separate reachable premises become a complete conjunction",
    "field-engine.test.ts hyperedge AND; field-coordinates.test.ts AND vs OR; equal-score-derivation-withdrawal.test.ts OR/AND", "typed hyperedge observe", "real-producer"),
  row("A08", "cheapest feasible complete explanation remains available",
    "cheap cost=400 over expensive=1200",
    "canonical strongest/first path hides cheap witness",
    "project-accepting-index.test.ts / explanation.ts cheapest complete witness", "index explanation_ids", "real-producer"),
  row("A09", "interrupt/resume observes the same pinned coverage",
    "truncated-zero → interrupted/open, not exhausted_empty",
    "interrupted zero rows become known-empty; cursor skips/duplicates",
    "mapNativeReaderPage + runRecall interrupted readers", "SQLite resume", "real-producer"),
  row("A10", "seed/adjacency/guard/binding regions remain represented",
    "four open regions after partial run",
    "queue omission or ANN absence creates false closure",
    "observers.test.ts / observer-index.test.ts seed/adjacency/guard/binding residuals", "observer residuals", "real-producer"),
  row("A11", "fair work, memory, reserved finalization hold",
    "finite region served; support cannot consume finalization reserve; native batch admission pays product-state cost",
    "high-bound refinement starves a finite region",
    "scheduleFairWork independent; grounded-revision.test.ts support budget; scale-delivery.test.ts native batch admission", "F5 work_units counters", "real-producer"),
  row("A12", "empty finite authorized scope can close; unavailable stays open",
    "exhausted_empty vs unavailable vs cancelled",
    "unavailable producer reported as complete empty",
    "runConditionalFieldRecall empty/unavailable readers", "MCP A12", "real-producer"),
  row("A13", "complete index may contain explicit unknown cause",
    "logical_index=complete and claim=unknown coexist",
    "every fact must be proved, or unresolved fields disappear",
    "projectAcceptingIndex; project-accepting-index.test.ts unknown-cause complete index", "MCP unknown-cause", "real-producer"),
  row("A14", "stable pages retain snapshot/query/authorization identity",
    "each qualified product is delivered once even when later observation inserts an earlier identity",
    "next page changes snapshot or reselects by old ranker",
    "scale-delivery.test.ts reverse/interleaved seeds and later relation pages; snapshot-cursor-continuation.test.ts exact token",
    "retained product delivery set in direct runtime; separate MCP/CLI continuation fixtures", "real-producer"),
  row("A15", "logical index, inline portion and payload status differ",
    "first page transport=partial, continuation set",
    "first page called full inline delivery",
    "pageMasqueradesAsFullIndex", "MCP A15", "real-producer"),
  row("A16", "output includes index roles/association/explanation at MCP/CLI",
    "handler results order equals index entries",
    "outer handler silently selects a different top-K",
    "createRecallHandler + CLI tools call", "MCP/CLI", "real-producer"),
  row("A17", "normal Recall never enqueues extraction or calls a provider",
    "provider_calls=0 garden_enqueue=0",
    "missing optional projection triggers remote work",
    "runRecall pendingGarden length", "handler counters", "real-producer"),
  row("A18", "write/restart/tombstone/revoke reaches the same reader",
    "tombstone hidden after reopen; mixed snapshot invalidates",
    "mixed generation or resurrected memory",
    "SQLite reopen + tombstone", "handler A18", "real-producer"),
  row("A19", "unknown/correlated evidence has honest claim state",
    "duplicate source sets do not mint independence",
    "duplicate paths/source count mint support",
    "F3 explanation leak check", "handler F3", "real-producer"),
  row("A20", "actual-budget representation respects feasibility",
    "page_budget is not a complete universe; memory_bytes=1 stays open",
    "density/identity caps masquerade as optimum",
    "F5 tiny memory index", "handler token cap", "real-producer"),
  row("A21", "normal entry remains target-only after retirement",
    "no ranking_authority/delivery_path/strategy_mix on target payload; retired flags not dispatched",
    "flags or worker dispatch reach the old decision chain",
    "conditional-field/assembly/retired-route-isolation.test.ts: real sources with poisoned providers and durable-write conservation",
    "MCP forbidden keys; conditional-field-acceptance/upgrade-consumer-acceptance.test.ts: handler encoding does not reselect or restore retired selector keys", "real-producer"),
  row("A22", "public/persisted old states have explicit dispositions",
    "persisted_old_receipts freeze-live; historical snapshots are not silently migrated; feedback unreachable-on-target",
    "silent reinterpretation, mixed schema, fallback decision route",
    "conditional-field-acceptance/snapshot-generation.test.ts: schema5 cursor upgrade, atomic rollback, restart and rebuild",
    "protocol retired-surface-compatibility.test.ts: old fields parse, explicit retired selector requests reject, strategy_mix forbidden on strict response; historical sealed snapshot replayability is a separate measurement gate", "real-producer"),
  row("B01", "product identity preserves object/hypothesis/program/binding/time",
    "five-tuple accepting key; program_state+time_state required on public entries",
    "equal object IDs merge incompatible states",
    "projectAcceptingIndex IndexEntry", "MCP index entries", "real-producer"),
  row("B02", "derivation scalar agrees with max-min; explanation coverage is separate",
    "AND=min OR=max; fixed_point ≠ witnesses complete",
    "numeric agreement claims all observers complete",
    "field-engine.ts createConditionalField / applyEvidenceEffect; field-engine.test.ts scalar fixed point vs support_work", "index support_work", "real-producer"),
  row("B03", "equal-score AND/OR withdraw c distinctly",
    "(a AND b) OR c → AND{a,b}; (a OR b) AND c → undefined",
    "both structures collapse to the same revision",
    "path-derivation.ts leafDerivation / withdrawDerivation; equal-score-derivation-withdrawal.test.ts", "none", "real-producer"),
  row("B04", "same-service history retains service binding across shared infrastructure",
    "service-role history hangs off uses_service; provider bridge does not unify another service",
    "all-high-grade provider bridge admits another service",
    "SQLite plant + compileConditionalFieldQuery / observeField", "MCP same-service query", "real-producer"),
  row("B05", "compiler interpretation coverage reaches the public index honestly",
    "omitted hypotheses keep interpretation_coverage=open while observed_coverage may complete",
    "completing one interpretation produces certainty about omitted hypotheses",
    "projectAcceptingIndex CompletenessReport", "MCP completeness", "real-producer"),
  row("B06", "revised-source evaluation agrees with fresh evaluation; mixed epochs invalidate",
    "epoch mismatch or stale/displaced/tampered issued token invalidates; only the current exact token refines retained state",
    "old source/model/interpretation silently refines a new epoch",
    "continuationInvalidated + interpretation_id; snapshot-cursor-continuation.test.ts exact token and interleaved instances",
    "paged resume; grounded-revision.test.ts same-count stronger seed, transition, derivation, root-map and source-revision equal fresh grounding", "real-producer"),
  row("B07", "recovered explanations preserve dependency versions and intermediate authorization",
    "revoked intermediate makes explanation unrecoverable even if grade is cached",
    "available endpoint or cached grade bypasses a revoked intermediate",
    "upgrade-expected.ts intermediateAuthorized", "expansion payload", "contract-only",
    "oracle helper intermediateAuthorized is not a production class"),
  row("B08", "bounded observations/joins/continuation retain unfinished regions",
    "grounding work advances through observation growth; zero/one-work and exhausted-memory requests terminate honestly",
    "memory eviction or cursor reset erases required work",
    "FIELD_RESUME + observer cursors; scale-delivery.test.ts 48-match tight work and 1,024-match memory pressure", "direct runtime plus separate small worker/RPC resume fixtures", "real-producer"),
  row("B09", "affordable complete alternative explanations remain available",
    "cheap complete witness retained when scalar winner differs",
    "winning scalar deletes a needed weaker/cheaper witness",
    "selectFeasibleWitnesses", "index explanation_ids", "real-producer"),
  row("B10", "output-level and witness-level reports preserve grain and exposure",
    "output grain credits output_id only; witness grain requires exposed witness_id",
    "output-only or forged receipt credits every path",
    "causal-usage-projection.ts attributeUsageReports; causal-usage-temporal-projection.test.ts output grain", "MCP usage handler", "real-producer"),
  row("B11", "duplicates, nonexposure, unknown use, correlation, ordinal scale stay distinct",
    "duplicate identity counted once; missing ≠ negative; nonexposure ≠ unused",
    "missing reports become negatives or discount arithmetic revises semantic truth",
    "causal-usage-projection.ts attributeUsageReports; causal-usage-temporal-projection.test.ts duplicate/nonexposure/unknown", "usage receipts", "real-producer"),
  row("B12", "scheduled plasticity and watermark consumers obey update ownership",
    "operational_feedback unreachable-on-target for PathRelation.strength",
    "new helper is safe but old background path still mutates unsupported strength",
    "causal-usage-projection.ts projectCausalUsageOntoPaths; causal-usage-temporal-projection.test.ts strength unchanged", "Garden path_plasticity_update", "real-producer"),
  row("B13", "upgraded fields reach SQLite, worker/RPC, MCP/CLI, paging, expansion, usage",
    "index product identity and interpretation_coverage survive real dispatch",
    "contract tests pass while dispatch flattens fields, invokes a provider, or selects again",
    "conditional-field-acceptance/snapshot-generation.test.ts: direct/worker source invalidation",
    "conditional-field-acceptance/lifecycle-usage.test.ts: worker product pages, expanded explanation references, same persisted witness exposure through restart and CLI usage; consumer-acceptance.test.ts: CLI Recall identity", "real-producer"),
  row("B14", "no-learner reference and completed necessity dispositions",
    "four mechanisms NOT_REQUIRED or BENEFIT_NOT_ESTABLISHED; finite examples ≠ learning gains",
    "a deferred selected mechanism is called complete",
    "causal-plasticity.ts USAGE_ADAPTATION_NECESSITY; causal-plasticity.test.ts no-learner dispositions", "operational no-learner Recall", "real-producer"),
  row("F1", "distinct programs/filters",
    "epsilon/empty/forward/reversed/blocked differ on one graph; public filters do not dump every fact",
    "all programs collapse to one field",
    "observeProgram + handler dimension/domain_tags", "MCP F1", "real-producer"),
  row("F2", "tombstone/scope/expired stay out of seed/intermediate/target/preview",
    "SECRET/GLOBAL/EXPIRED absent",
    "ineligible rows appear in index or preview",
    "runRecall authorized_scopes", "handler F2", "real-producer"),
  row("F3", "witness identity does not leak across objects",
    "explanation_ids do not copy another object's witnesses; unknown remains representable",
    "cross-object witness ids",
    "runRecall + handler", "MCP F3", "real-producer"),
  row("F4", "40-match/32-cap resume equals full observation",
    "40-match worker pages and 180-match direct pages concatenate to full ids without skips or duplicates",
    "32-cap silently drops remainder",
    "conditional-field-acceptance/lifecycle-usage.test.ts: 40 synthetic matches through direct/real worker; scale-delivery.test.ts: 180 matches in 1,024-source SQLite corpus",
    "same test: complete ordered product equality, exact count/identity set, payload and pinned page identity", "real-producer"),
  row("F5", "work_units/memory_bytes/token_estimate are actual",
    "nativeVisits≤work_units; memory_bytes=1 not complete 31; tokens follow preview bytes",
    "token_estimate frozen at 1",
    "countingReaders + encodeIndexResults", "handler F5", "real-producer"),
  row("F6", "pin and preview are not mixed across snapshot commit",
    "one generation of previews; mixed before/after forbidden",
    "mixed-generation complete payload",
    "conditional-field-acceptance/snapshot-generation.test.ts: same-timestamp content/scope/lifecycle mutations invalidate direct and real worker continuations",
    "stale index is empty/invalidated; fresh request has a different snapshot; producer-consumer-counterexamples.test.ts checks direct handler previews", "real-producer"),
  row("F7", "midnight continuation is invalidated or same-instance",
    "interpretation_clock change invalidates or keeps identity; no two-day splice",
    "pages spliced across midnight",
    "conditional-field-acceptance/lifecycle-usage.test.ts: real worker nonempty pages across midnight",
    "same test: query/snapshot/interpretation/result/as_of and entry time_state stay pinned; direct/worker expired-token rejection remains separate", "real-producer"),
  row("F8", "worker-port preview/RPC residual",
    "content_preview is the pinned source excerpt, not omitted placeholder",
    "worker port supplies empty preview map so MCP hydrates [payload omitted]",
    "executeRecall conditionalFieldPort branch", "MCP encodeIndexResults", "real-producer"),
  row("NT3", "A09/A18 lifecycle tests are real SQLite, not stubs",
    "tombstone restart and interrupted-zero use openSourceSlice",
    "stubbed lifecycle always-green",
    "source-lifecycle-oracle + acceptance", "handler A18", "real-producer"),
  row("S13", "worker + CLI planted slice",
    "CLI in-process matches handler index identity",
    "CLI marshalling uses stub deps while claiming planted slice",
    "conditional-field-acceptance/consumer-acceptance.test.ts: CLI Recall matches planted handler index",
    "conditional-field-acceptance/lifecycle-usage.test.ts: real worker MCP output/explanation identity and same delivery accepted by CLI usage after restart; compositional boundary coverage", "real-producer")
]);

export function requiredIds(): readonly string[] {
  const a = Array.from({ length: 22 }, (_, index) => `A${String(index + 1).padStart(2, "0")}`);
  const b = Array.from({ length: 14 }, (_, index) => `B${String(index + 1).padStart(2, "0")}`);
  return [...a, ...b, "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "NT3", "S13"];
}

function row(
  id: string,
  requirement: string,
  expected: string,
  planted_failure: string,
  producer: string,
  consumer: string,
  binding: CoverageBinding,
  incomplete_reason?: string
): CoverageRow {
  return Object.freeze({
    id,
    requirement,
    expected,
    planted_failure,
    producer,
    consumer,
    binding,
    ...(incomplete_reason === undefined ? {} : { incomplete_reason })
  });
}
